[package]
name = "rookup-common"
description = "Common utilities used for the Rookup multiplexer and proxy"
version = "0.1.0"
edition = "2021"

[build-dependencies]
rookup-common-build = { path = "./rookup-common-build" }

[dependencies]
rookup-common-base = { path = "./rookup-common-base" }
