[package]
name = "rookup-spcomp"
description = "Proxy for SourcePawn compilers that integrates with Rookup"
version = "0.2.0"
edition = "2021"
license = "GPL-3.0-or-later"
authors = ["b0mbie"]

[dependencies]
anyhow = "1.0.96"
rookup-common = { path = "../rookup-common" }
